import React from 'react';
import Head from 'next/head';
import OrgDirectoryHeader from '../../components/OrgDirectoryHeader';
import OrgDirectorySidebar from '../../components/OrgDirectorySidebar';
import OrgDirectoryGrid from '../../components/OrgDirectoryGrid';

const DirectoryHead = () => (
  <Head>
    <title>Directory - Jupiter</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default function Directory() {
  return (
    <>
      <DirectoryHead />
      <main>
        <div className="grid md:grid-cols-6 gap-x-4 p-5">
          <OrgDirectoryHeader />
        </div>
        <div className="grid md:grid-cols-6 grid-cols-3 gap-x-4 grid-rows-2 items-center h-full p-5 w-full">
          <OrgDirectorySidebar />
          <OrgDirectoryGrid />
        </div>
      </main>
    </>
  );
}
