import React from "react";
import Head from 'next/head'
import OrganizationCard from '../components/OrganizationCard'
import DemoOrganizations from '../DemoOrganizations';
import orgList from '../demoOrganizations.json';
import { Row, Col } from 'react-simple-flex-grid';
import "react-simple-flex-grid/lib/main.css";
import Link from 'next/link'

export default function Directory() {
    return (
        <div>
            <Head>
                <title>Jupiter Directory</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <p style={{ position: 'relative', paddingLeft: 20, fontSize: 22, fontWeight: "450" }}>Organization Directory</p>
            <Row justify="left">
                <div className="organizations-grid">
                    {orgList.map(org =>
                        <Col
                            key={org.name}
                            xs={{ span: 2 }} sm={{ span: 3 }} md={{ span: 3 }}
                            lg={{ span: 3 }} xl={{ span: 2 }}>
                            <div className="OrgListing">
                                <Link href="/organization">
                                    <a><OrganizationCard name={org.name} imageLink={org.imageLink} tags={org.tags} /></a>
                                </Link>
                            </div>
                        </Col>
                    )}
                </div>
            </Row>
        </div>
    )
}