import React from 'react';
import Head from 'next/head';
import OrganizationCard from '../components/OrganizationCard';
import DemoOrganizations from '../DemoOrganizations';
import orgList from '../demoOrganizations.json';
import { Row, Col } from 'react-simple-flex-grid';
import 'react-simple-flex-grid/lib/main.css';
import Link from 'next/link';

const DirectoryHead = () => (
  <Head>
    <title>Directory - Jupiter</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default function Directory() {
  return (
    <>
      <DirectoryHead />
      <main>
<<<<<<< HEAD
        <div className="grid md:grid-cols-6 grid-cols-3 gap-x-4 md:grid-rows-4 grid-rows-6 items-center justify-center h-full p-5 w-full">
=======
        <div className="p-5">
>>>>>>> 9cb4602 (Update directory card)
          <OrgDirectoryHeader />
        </div>
        <div className="grid md:grid-cols-6 grid-cols-3 gap-x-4 grid-rows-2 items-center h-full p-5 w-full">
          <OrgDirectorySidebar />
          <OrgDirectoryGrid />
        </div>
      </main>
    </>
  );
}
