import EventsSidebar from './../components/EventsSidebar';
import EventsHeader from '../components/EventsHeader';
import React from 'react';
import Head from 'next/head';
import EventList from '../components/EventList';

export default function Events() {
  return (
    <>
      <Head>
        <title>Jupiter Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="p-4">
          <EventsHeader />
        </div>
        <div className="md:flex md:flex-row">
          <EventsSidebar />
          <EventList />
        </div>
      </main>
    </>
  );
}
