import Head from 'next/head';
import { EventHeader } from '../components/Header';
import EventCalendar from '../components/EventCalendar';

const Events = () => {
  return (
    <>
      <Head>
        <title>Jupiter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="md:pl-72">
        <EventHeader />
        <EventCalendar index={0} />
        <EventCalendar index={1} />
      </main>
    </>
  );
};

export default Events;
